"""
Regression test for PracticeGenerator never actually using SymPy for math
items.

Root cause: PracticeGenerator.__init__ never sets `self._math_generator`,
but `_generate_math_item` checks `if self._math_generator is None:` before
lazily constructing it. Since the attribute doesn't exist at all, that check
raises AttributeError, which is caught by `_generate_math_item`'s broad
`except Exception` and silently falls back to
`quality_service.generate_with_context` (OpenAI) for every math item, every
time. SymPy generation was effectively dead code - all "math" practice items
were actually generated by the model, which explains why users occasionally
saw generic placeholder distractors on math questions: the model's JSON
response sometimes omitted "choices", triggering the fallback distractor
generator.
"""

from unittest.mock import MagicMock

from src.services.practice.generator import PracticeGenerator


def test_math_generation_uses_sympy_not_openai_fallback(monkeypatch):
    """A math topic should be generated via MathGenerator (SymPy), not via
    quality_service.generate_with_context (OpenAI)."""
    generator = PracticeGenerator()

    # If the OpenAI fallback is hit, this will raise -- proving the SymPy
    # path was bypassed due to the missing _math_generator attribute.
    generator.quality_service.generate_with_context = MagicMock(
        side_effect=AssertionError(
            "OpenAI fallback was used for a math topic - SymPy path failed"
        )
    )

    item = generator.generate_practice_item(
        subject="Math", topic="Linear Equations", difficulty_level=5
    )

    assert item["question_text"]
    assert len(item["choices"]) == 4
    generator.quality_service.generate_with_context.assert_not_called()


def test_math_generator_lazily_constructed_once():
    """_math_generator should be None before first use and populated after,
    without raising AttributeError."""
    generator = PracticeGenerator()
    assert generator._math_generator is None

    generator.generate_practice_item(
        subject="Math", topic="Linear Equations", difficulty_level=5
    )

    assert generator._math_generator is not None
